"""
ORM model for the training programs table.
"""

from sqlalchemy import Column, Integer, String, DateTime, Enum, ForeignKey, Boolean
from sqlalchemy.sql import func
from sqlalchemy.orm import relationship
import enum
from ..base import Base

class ProgramType(enum.Enum):
    """
    Enumeration of training program types.
    
    Attributes:
        HYPERTROPHY: Programs focused on muscle growth
        STRENGTH: Programs focused on strength development
        PEAKING: Programs focused on peaking for competition
    """
    HYPERTROPHY = "hypertrophy"
    STRENGTH = "strength"
    PEAKING = "peaking"

class TrainingProgram(Base):
    """
    Training Program model for the FitCoach AI application.
    
    Attributes:
        id: Unique identifier for the training program
        user_id: ID of the user who owns the program
        name: Name of the training program
        description: Optional description of the program
        program_type: Type of program (hypertrophy, strength, peaking)
        duration_weeks: Total duration of the program in weeks
        # ...existing code...
        is_ai_generated: Whether the program was generated by AI
        created_at: Creation date of the record
        updated_at: Date of the last update to the record
        
    Relationships:
        user: Relationship with the user who owns the program
        training_weeks: Relationship with the weeks that make up the program
    """
    __tablename__ = "training_programs"
    
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    name = Column(String, nullable=False)
    description = Column(String, nullable=True)
    program_type = Column(Enum(ProgramType), nullable=False)
    duration_weeks = Column(Integer, nullable=False)
    is_ai_generated = Column(Boolean, default=False)
    
    
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())
    
    # Relationships
    user = relationship("User", back_populates="training_programs")
    training_weeks = relationship("TrainingWeek", back_populates="training_program", cascade="all, delete-orphan")
    
    def __repr__(self):
        """String representation of the training program."""
        return f"<TrainingProgram {self.id}: {self.name}>" 