# ejercicios.py

ejercicios = [
    "Press de banca plano",
    "Press de banca inclinado",
    "Press de banca declinado",
    "Press de banca con agarre cerrado",
    "Press de banca con agarre ancho",
    "Press de banca guillotina",
    "Press de banca pausa",
    "Press de banca con cadenas",
    "Press de banca con bandas elásticas",
    "Press de banca spoto",
    "Press de banca larsen",
    "Pullover con barra",
    "Press de pecho plano con mancuernas",
    "Press de pecho inclinado con mancuernas",
    "Press de pecho declinado con mancuernas",
    "Aperturas planas",
    "Aperturas inclinadas",
    "Aperturas declinadas",
    "Press martillo",
    "Pullover con mancuerna",
    "Press palof con mancuerna",
    "Press de pecho en máquina",
    "Press inclinado en máquina",
    "Press declinado en máquina",
    "Peck deck (mariposa)",
    "Contractora de pectoral",
    "Press convergente",
    "Press divergente",
    "Cruces de poleas altas",
    "Cruces de poleas bajas",
    "Cruces de poleas medias",
    "Press de pecho en polea",
    "Pullover en polea alta",
    "Aperturas en polea unilateral",
    "Flexiones normales",
    "Flexiones diamante",
    "Flexiones anchas",
    "Flexiones inclinadas (pies elevados)",
    "Flexiones declinadas (manos elevadas)",
    "Flexiones arqueras",
    "Flexiones con palmada",
    "Flexiones hindu",
    "Flexiones pike",
    "Peso muerto convencional",
    "Peso muerto sumo",
    "Peso muerto rumano",
    "Peso muerto con piernas rígidas",
    "Peso muerto deficit",
    "Peso muerto desde bloques",
    "Peso muerto pausa",
    "Peso muerto con cadenas",
    "Peso muerto con bandas elásticas",
    "Peso muerto snatch grip",
    "Peso muerto trap bar",
    "Peso muerto Jefferson",
    "Peso muerto a una pierna",
    "Remo con barra",
    "Remo pendlay",
    "Remo yates",
    "Remo invertido",
    "High pulls",
    "Remo deficit",
    "Remo desde bloques",
    "Remo con mancuerna a una mano",
    "Remo con ambas mancuernas",
    "Remo serruchado",
    "Peso muerto con mancuernas",
    "Pullover para espalda",
    "Remo renegado",
    "Remo en máquina horizontal",
    "Remo en máquina inclinado",
    "Pulldown frontal",
    "Pulldown tras nuca",
    "Remo en máquina convergente",
    "Remo en T",
    "Jalones al frente",
    "Jalones tras nuca",
    "Jalones con agarre cerrado",
    "Jalones con agarre ancho",
    "Jalones unilaterales",
    "Remo en polea baja",
    "Remo en polea alta",
    "Remo unilateral en polea",
    "Pulldowns con cuerda",
    "Dominadas pronadas",
    "Dominadas supinadas",
    "Dominadas neutras",
    "Dominadas arqueras",
    "Dominadas con toalla",
    "Dominadas L-sit",
    "Remo invertido en barra",
    "Remo australiano",
    "Press militar",
    "Press tras nuca",
    "Press frontal sentado",
    "Press militar pausa",
    "Press militar desde bloques",
    "Press militar con cadenas",
    "Press militar con bandas elásticas",
    "Elevaciones frontales con barra",
    "Remo al mentón",
    "Bradford press",
    "Press de hombros con mancuernas",
    "Press Arnold",
    "Elevaciones laterales",
    "Elevaciones frontales",
    "Elevaciones posteriores",
    "Press unilateral",
    "Press alterno",
    "Remo al mentón con mancuernas",
    "Press de hombros en máquina",
    "Elevaciones laterales en máquina",
    "Elevaciones posteriores en máquina",
    "Remo al mentón en máquina",
    "Elevaciones laterales en polea",
    "Elevaciones frontales en polea",
    "Elevaciones posteriores en polea",
    "Press de hombros en polea",
    "Remo al mentón en polea",
    "Flexiones pike",
    "Flexiones verticales (parado de manos)",
    "Flexiones hindu para hombros",
    "Caminata de cangrejo",
    "Press militar",
    "Press frontal sentado",
    "Elevaciones frontales con barra",
    "Press de hombros con mancuernas",
    "Press Arnold",
    "Elevaciones frontales",
    "Press unilateral",
    "Press alterno",
    "Press de hombros en máquina",
    "Elevaciones frontales en máquina",
    "Elevaciones frontales en polea",
    "Press de hombros en polea",
    "Flexiones pike",
    "Flexiones verticales (parado de manos)",
    "Press militar (activación)",
    "Remo al mentón",
    "Elevaciones laterales",
    "Press Arnold",
    "Remo al mentón con mancuernas",
    "Elevaciones laterales en máquina",
    "Remo al mentón en máquina",
    "Elevaciones laterales en polea",
    "Remo al mentón en polea",
    "Flexiones pike (activación)",
    "Remo con barra",
    "Remo pendlay",
    "Remo yates",
    "Elevaciones posteriores",
    "Remo con mancuerna",
    "Remo serruchado",
    "Elevaciones posteriores en máquina",
    "Remo en máquina",
    "Peck deck inverso",
    "Elevaciones posteriores en polea",
    "Face pulls",
    "Remo en polea alta",
    "Remo invertido",
    "Remo australiano",
    "Encogimientos con barra",
    "Remo al mentón",
    "Peso muerto (porción superior)",
    "Cargadas de potencia",
    "High pulls",
    "Encogimientos snatch grip",
    "Encogimientos con mancuernas",
    "Remo al mentón con mancuernas",
    "Encogimientos unilaterales",
    "Encogimientos en máquina",
    "Remo al mentón en máquina",
    "Encogimientos en polea",
    "Remo al mentón en polea",
    "Face pulls (trapecio medio)",
    "Encogimientos sin peso",
    "Remo invertido (activación)",
    "Remo con barra",
    "Remo pendlay",
    "Remo yates",
    "Remo con mancuerna",
    "Remo serruchado",
    "Remo con ambas mancuernas",
    "Remo en máquina horizontal",
    "Remo en máquina inclinado",
    "Remo convergente",
    "Remo en polea baja",
    "Remo en polea alta",
    "Face pulls",
    "Remo unilateral en polea",
    "Remo invertido",
    "Remo australiano",
    "Dominadas (activación)",
    "Curl de bíceps parado",
    "Curl de bíceps sentado",
    "Curl martillo con barra",
    "Curl 21s",
    "Curl de concentración con barra",
    "Curl predicador con barra",
    "Curl drag",
    "Curl con barra EZ",
    "Curl con barra recta",
    "Curl de bíceps con mancuernas",
    "Curl martillo",
    "Curl alterno",
    "Curl de concentración",
    "Curl predicador con mancuerna",
    "Curl Zottman",
    "Curl inclinado",
    "Curl en máquina",
    "Curl predicador en máquina",
    "Curl de pie en máquina",
    "Curl de bíceps en polea baja",
    "Curl de bíceps en polea alta",
    "Curl martillo en polea",
    "Curl predicador en polea",
    "Curl concentrado en polea",
    "Dominadas supinadas",
    "Dominadas neutras",
    "Remo invertido supinado",
    "Press francés",
    "Press francés de pie",
    "Press de banca agarre cerrado",
    "Press de banca agarre cerrado pausa",
    "Press de banca agarre cerrado desde bloques",
    "Extensiones tras nuca con barra",
    "Press francés con barra EZ",
    "Press francés con mancuerna",
    "Extensiones tras nuca con mancuerna",
    "Kickbacks",
    "Press francés unilateral",
    "Press francés martillo",
    "Press francés en máquina",
    "Extensiones de tríceps en máquina",
    "Fondos en máquina",
    "Extensiones de tríceps en polea alta",
    "Extensiones de tríceps en polea baja",
    "Press francés en polea",
    "Kickbacks en polea",
    "Extensiones tras nuca en polea",
    "Fondos en paralelas",
    "Fondos entre bancos",
    "Flexiones diamante",
    "Flexiones con agarre cerrado",
    "Curl de muñeca con barra",
    "Curl de muñeca inverso con barra",
    "Curl martillo con barra",
    "Paseo del granjero con barra",
    "Curl de muñeca con mancuernas",
    "Curl de muñeca inverso con mancuernas",
    "Curl martillo",
    "Paseo del granjero con mancuernas",
    "Rotaciones de muñeca",
    "Curl de muñeca en máquina",
    "Curl de muñeca inverso en máquina",
    "Curl de muñeca en polea",
    "Curl de muñeca inverso en polea",
    "Curl martillo en polea",
    "Flexiones en puños",
    "Colgarse de barra",
    "Dominadas con toalla",
    "Sentadilla back squat (high bar)",
    "Sentadilla back squat (low bar)",
    "Sentadilla frontal",
    "Sentadilla búlgara con barra",
    "Sentadilla hack",
    "Sentadilla pausa",
    "Sentadilla desde bloques",
    "Sentadilla con cadenas",
    "Sentadilla con bandas elásticas",
    "Sentadilla pin squat",
    "Sentadilla box squat",
    "Sentadilla anderson",
    "Sentadilla jump",
    "Zancadas con barra",
    "Zancadas caminando con barra",
    "Zancadas frontales con barra",
    "Step ups con barra",
    "Sentadilla goblet",
    "Zancadas con mancuernas",
    "Zancadas frontales",
    "Zancadas laterales",
    "Zancadas inversas",
    "Sentadilla búlgara con mancuernas",
    "Step ups",
    "Extensiones de cuádriceps",
    "Prensa de piernas",
    "Prensa hack",
    "Sentadilla en máquina Smith",
    "Sentadilla hack en máquina",
    "Sentadillas aire",
    "Sentadillas jump",
    "Sentadillas pistol",
    "Zancadas frontales",
    "Step ups",
    "Sentadillas cosacas",
    "Peso muerto rumano",
    "Peso muerto con piernas rígidas",
    "Peso muerto deficit rumano",
    "Peso muerto rumano desde bloques",
    "Peso muerto rumano pausa",
    "Buenos días",
    "Buenos días con barra alta",
    "Buenos días con barra baja",
    "Buenos días sentado",
    "Peso muerto a una pierna",
    "Sentadilla sumo (activación)",
    "Peso muerto rumano con mancuernas",
    "Peso muerto a una pierna con mancuerna",
    "Buenos días con mancuerna",
    "Zancadas inversas (activación)",
    "Curl femoral acostado",
    "Curl femoral sentado",
    "Curl femoral de pie",
    "Peso muerto en máquina",
    "Curl femoral en polea",
    "Patadas hacia atrás en polea",
    "Puente de glúteos (activación femoral)",
    "Curl nórdico",
    "Deslizamientos de talón",
    "Hip thrust con barra",
    "Hip thrust pausa",
    "Hip thrust desde bloques",
    "Puente de glúteos con barra",
    "Peso muerto sumo",
    "Sentadilla sumo",
    "Sentadilla sumo con barra alta",
    "Sentadilla sumo con barra baja",
    "Peso muerto rumano",
    "Zancadas inversas con barra",
    "Zancadas laterales con barra",
    "Hip thrust con mancuerna",
    "Puente de glúteos con mancuerna",
    "Zancadas inversas",
    "Zancadas laterales",
    "Peso muerto rumano con mancuernas",
    "Sentadilla sumo con mancuerna",
    "Patadas de glúteo en máquina",
    "Extensiones de cadera en máquina",
    "Abducción de cadera en máquina",
    "Prensa de piernas (activación)",
    "Patadas de glúteo en polea",
    "Extensiones de cadera en polea",
    "Abducción de cadera en polea",
    "Patadas laterales en polea",
    "Puentes de glúteos",
    "Hip thrust",
    "Zancadas inversas",
    "Sentadillas sumo",
    "Patadas de glúteo",
    "Caminata lateral",
    "Sentadilla sumo",
    "Sentadilla sumo con barra alta",
    "Sentadilla sumo con barra baja",
    "Sentadilla cossack con barra",
    "Sentadilla sumo con mancuerna",
    "Zancadas laterales",
    "Sentadilla cossack con mancuerna",
    "Aducción con mancuerna acostado",
    "Aducción de cadera en máquina",
    "Prensa de piernas con pies juntos",
    "Sentadilla sumo en máquina",
    "Aducción de cadera en polea",
    "Cruces de piernas en polea",
    "Sentadillas sumo",
    "Zancadas laterales",
    "Sentadillas cossack",
    "Aducción isométrica",
    "Elevaciones de pantorrilla de pie con barra",
    "Elevaciones de pantorrilla sentado con barra",
    "Elevaciones de pantorrilla con mancuernas",
    "Elevaciones de pantorrilla a una pierna",
    "Elevaciones de pantorrilla sentado",
    "Elevaciones de pantorrilla en máquina de pie",
    "Elevaciones de pantorrilla en máquina sentado",
    "Elevaciones de pantorrilla en prensa",
    "Elevaciones de pantorrilla en hack squat",
    "Elevaciones de pantorrilla en polea",
    "Elevaciones de pantorrilla unilateral en polea",
    "Elevaciones de pantorrilla",
    "Elevaciones de pantorrilla a una pierna",
    "Saltos de pantorrilla",
    "Caminata en puntas",
    "Rollouts con barra",
    "Crunches con barra",
    "Sit-ups con barra",
    "Crunches con mancuerna",
    "Sit-ups con mancuerna",
    "Dead bugs con mancuerna",
    "Crunches en máquina",
    "Elevaciones de piernas en máquina",
    "Crunches en polea alta",
    "Crunches en polea baja",
    "Elevaciones de rodillas en polea",
    "Crunches",
    "Sit-ups",
    "Elevaciones de piernas",
    "Bicicleta",
    "Dead bugs",
    "V-ups",
    "Hollow body holds",
    "Crunches invertidos",
    "Flexiones laterales con barra",
    "Giros rusos con barra",
    "Flexiones laterales con mancuerna",
    "Giros rusos con mancuerna",
    "Leñador con mancuerna",
    "Crunches laterales con mancuerna",
    "Flexiones laterales en máquina",
    "Giros en máquina",
    "Flexiones laterales en polea",
    "Giros en polea",
    "Leñador en polea",
    "Crunches laterales en polea",
    "Plancha lateral",
    "Crunches laterales",
    "Giros rusos",
    "Escaladores laterales",
    "Plancha lateral con elevación",
    "Rollouts con barra",
    "Paseo del granjero con barra",
    "Cargadas frontales (estabilización)",
    "Sentadillas frontales (estabilización)",
    "Paseo del granjero con mancuernas",
    "Plancha con arrastre de mancuerna",
    "Dead bugs con mancuerna",
    "Crunches en máquina",
    "Rotaciones en máquina",
    "Pallof press",
    "Rotaciones en polea",
    "Anti-extensión en polea",
    "Plancha",
    "Plancha lateral",
    "Dead bugs",
    "Bird dogs",
    "Mountain climbers",
    "Hollow body holds",
    "Bear crawls",
    "Plancha con movimiento",
    "Buenos días",
    "Buenos días con barra alta",
    "Buenos días con barra baja",
    "Buenos días sentado",
    "Peso muerto",
    "Peso muerto rumano",
    "Hiperextensiones con barra",
    "Buenos días con mancuerna",
    "Hiperextensiones con mancuerna",
    "Peso muerto con mancuernas",
    "Hiperextensiones en máquina",
    "Extensiones de espalda en máquina",
    "Buenos días en polea",
    "Extensiones de espalda en polea",
    "Hiperextensiones",
    "Extensiones de espalda",
    "Superman",
    "Bird dogs",
    "Plancha inversa",
    "Encogimientos con barra (activación)",
    "Flexiones de cuello con mancuerna",
    "Extensiones de cuello con mancuerna",
    "Flexiones laterales de cuello",
    "Flexiones de cuello en máquina",
    "Extensiones de cuello en máquina",
    "Flexiones laterales en máquina",
    "Flexiones de cuello en polea",
    "Extensiones de cuello en polea",
    "Flexiones laterales en polea",
    "Flexiones de cuello",
    "Extensiones de cuello",
    "Flexiones laterales de cuello",
    "Rotaciones de cuello",
    "Puente de luchador",
    "Sentadilla a press",
    "Cargada y envión",
    "Arrancada",
    "Cargada de potencia",
    "Snatch grip deadlift",
    "Thruster",
    "Cargada desde bloques",
    "Cargada deficit",
    "Arrancada desde bloques",
    "Arrancada deficit",
    "Burpees con mancuernas",
    "Sentadilla a press con mancuernas",
    "Swing con mancuerna",
    "Turkish get-up",
    "Remo a upright row",
    "Clean and press",
    "Leñador rotacional",
    "Patrones de movimiento funcional",
    "Ejercicios multiplanares",
    "Burpees",
    "Mountain climbers",
    "Bear crawls",
    "Crab walks",
    "Movimientos de animal flow"
]
